### ISSUE TITLE
Proposal Feedback

### ISSUE THREAD

**Issue by Chris210634** [nupurdivekar/cs506#1]
Hi,

The proposal sounds like a good plan, but it is somewhat vague. 

I suggest that you start early and look at the Kaggle dataset you want to work on carefully to make sure you understand the problem. 

For example, if you want to work on the NIH Chest X-ray dataset, make sure:
 - You can access the dataset  (decide if you want to work with the dataset on Kaggle or locally)
 - You know what you are trying to predict (the inputs and outputs to your model)
 - You have the hardware capabilities you need to run the model you want to run.

**Comment by aarsh-mehta** [comment]
Updated readme
